flags: {}
extra-package-dbs: []
extra-deps:
    - yesod-markdown-0.12.6.11
    - yesod-auth-oauth2-0.6.3.4
    - hoauth2-1.16.0
    - tz-0.1.3.5
    - th-utilities-0.2.4.3
    - haskell-src-exts-simple-1.23.0.0
    - haskell-src-exts-1.23.1
    - wai-middleware-throttle-0.3.0.1@sha256:8da81c156abbcaee3bdda60763bb9780ae1b9ff447bd5580202c0e0f5f8f7bcb,2522
    - token-bucket-0.1.0.1
    - lti13-0.2.0.3
    - yesod-auth-lti13-0.2.0.3
    - oidc-client-0.6.0.0
    - classy-prelude-yesod-1.5.0

packages:
- Carnap/
- Carnap-Server/
- Carnap-Client/
resolver: lts-18.7
