flags: {}
extra-package-dbs: []
extra-deps:
    - yesod-markdown-0.12.6.3
    - yesod-auth-oauth2-0.6.1.3
    - hoauth2-1.8.9
    # - uri-bytestring-aeson-0.1.0.8
    - diagrams-builder-0.8.0.5
    - tz-0.1.3.4@sha256:bd311e202b8bdd15bcd6a4ca182e69794949d3b3b9f4aa835e9ccff011284979,5086
    - th-utilities-0.2.4.0@sha256:ba19cd8441aa43dbaed40e9055bb5a7cbd7cf9e154f5253c6bf9293af8b1f96b,1869
    - haskell-src-exts-simple-1.22.0.0
    - haskell-src-exts-1.22.0
    - git: https://github.com/yesodweb/persistent.git
      commit: 1cdadc10405e9e3b1e0e73e2c1d6ec84eed69a53
      subdirs:
          - persistent
          - persistent-sqlite
          - persistent-postgresql
          - persistent-template
          - persistent-qq
    - lti13-0.2.0.0
    - yesod-auth-lti13-0.2.0.0
    - oidc-client-0.5.1.0

# :( persistent bug fix requires a git version, which means we have to turn off
# version checking in every yesod project
allow-newer: true

packages:
- Carnap/
- Carnap-Server/
- Carnap-Client/
#resolver: lts-6.25
#resolver: lts-12.26
#resolver: lts-14.27
resolver: lts-16.11
