# templates/homepage.hamlet
HomepageWelcome: Welcome to Carnap.io
HomepageSubtitle: A formal logic framework for Haskell
HomepageHeader: Background
HomepageText1: Carnap is a free and open software framework written in
HomepageText2: for teaching and studying formal logic. Carnap powers logic courses at
HomepageText3: dozens of colleges and universities
HomepageText4: around the world.
HomepageText5: If you're a student in a course that uses Carnap, please follow the links at the top of the page to log in and to access course materials.
HomepageText6: If you're just curious about Carnap, you can find some general information on our
HomepageText7: about
HomepageText8: page. If you're interested in the project, and would like to use Carnap in a class you're teaching, or get involved in some other way, please feel free to 
HomepageText9: get in touch!
