# templates/homepage.hamlet
HomepageWelcome: Carnap.io sitesine hoş geldiniz!
HomepageSubtitle: Haskell için formel mantık çerçevesi
HomepageHeader: Arkaplan
HomepageTextPrefix1: Carnap, formel mantık öğretmek ve öğrenmek üzere
HomepageTextLink1: Haskell
HomepageTextSuffix1: dilinde yazılmış ücretsiz ve açık yazılım çerçevesidir.
HomepageTextPrefix2: Carnap, dünya çapında
HomepageTextLink2: düzinelerce kolej ve üniversitede
HomepageTextSuffix2: okutulan mantık derslerine güç katar.
HomepageText3: Carnap kullanan bir derse kayıtlı öğrenciyseniz, oturum açmak ve ders içeriğine erişmek için lütfen sayfanın üst kısmındaki bağlantıları izleyin.
HomepageTextPrefix4: Carnap'ı sadece merak ediyorsanız, bazı genel bilgileri sitemizin
HomepageTextLink4: hakkında
HomepageTextSuffix4: sayfasında bulabilirsiniz..
HomepageTextPrefix5: Projeyle ilgileniyorsanız ve Carnap'ı mantık öğrettiğiniz bir sınıfta kullanmak veya projeye başka bir şekilde dahil olmak istiyorsanız lütfen
HomepageTextLink5: irtibata geçmekten çekinmeyiniz!

# templates/infopage.hamlet
InfopageAboutCarnap: Carnap Hakkında
InfopageWhatIs: Carnap Nedir?
InfopageWhatFor: Carnap Ne İşe Yarar?
InfopageHowToUse: Carnap'ı Nasıl Kullanabilirim?
InfopageWhyName: Neden “Carnap”?
InfopageWhoUses: Carnap'ı Kim Kullanır?
InfopageHowWorks: Carnap Nasıl Çalışır?
InfopageHowHelp: Nasıl Dahil Olabilirim?
InfopageCarnapQuote1: “Soyut dilsel biçimlerin kabulü ya da reddi, tıpkı herhangi bir bilim dalındaki diğer herhangi bir dil biçiminin kabulü ya da reddi gibi, nihai olarak, elde edilen sonucun gereken çabanın miktarı ve karmaşıklığına oranı yani araç olarak verimlilik tarafından kararlaştırılır. Pratik kullanımdaki başarılarını veya başarısızlıklarını test etmek yerine, belirli dil biçimlerine dogmatik yasaklar koymak, yararsızdan daha kötüdür; kesinlikle zararlıdır çünkü bilimsel ilerlemeyi engelleyebilir.
InfopageCarnapQuote2: ...
Herhangi bir araştırma alanında çalışanlara yararlı buldukları herhangi bir ifade biçimini kullanma özgürlüğü tanıyacağız; sahada çalışmak hiçbir yararlı işlevi olmayan biçimlerin er ya da geç ortadan kaldırılmasına yol açar. Dikkatli olmak istiyoruz: iddialarda bulunurken ve onları incelerken eleştirel ama dilsel biçimleri kabul ederken hoşgörülü olmak istiyoruz.”
InfopageCarnapQuoteSource: "Görgücülük, Anlambilim ve Varlıkbilim," Anlam ve Zorunluluk, 1956, 2. baskı.
InfopageWhatIsText: Carnap, formel diller, mantık ve anlambilim oluşturmak ve keşfetmek için ücretsiz ve açık kaynaklı bir Haskell yapısıdır. Dilleri hızlı ve kolay bir şekilde tanımlamanıza, bu diller için mantıklar oluşturmanıza ve anlamlarını belirlemenize olanak tanır. Ardından Carnap, yarattığınız mantığı kullanarak çeşitli formel dizgelerde kanıtları nasıl denetleyeceğinizi, bileşik ifadelerin anlamlarını nasıl bulacağınızı ve çok daha fazlasını bulmak üzere kendi tanımladığınız yönergeleri kullanır.

InfopageDemos: Tanıtım
InfopageDemosHere: Carnap ile yapabileceklerinize birkaç küçük örnek:
InfopageDemosText1: Bu, önermeler mantığında kullanılan Kalish ve Montague Dizgesine uygun bir kanıt kutusudur. Kanıt kutusuna yazarak kanıtlamayı doğrudan değiştirebilir ve sağ taraftaki çizgi süslemeleri üzerinde fareyi gezdirerek yaptığınız değişikliklerin etkilerini görebilirsiniz.
InfopageDemosText2: Bu, geliştirilmekte olan kanıtlamanın yapısını görsel olarak da gösteren, önermeler mantığında kullanılan Kalish ve Montague Dizgesine uygun yorumlamalı bir kanıt kutusudur.
InfopageDemosText3: Bu, Hardegree'in Montague Dizgesi çeşitlemesine uygun yorumlamalı bir kanıt kutusudur.
InfopageDemosTextPrefix4: Bu,
InfopageDemosTextItalics4: The Logic Book
InfopageDemosTextSuffix4: adlı yapıttaki kuralları kullanan ve kanıtlamanın yapısını görsel olarak Fitch tarzında yorumlayan Fitch dizgeli bir kanıt kutusudur.
InfopageDemosText5: Bu, Russell Teoreminin bir kanıtlamasını gösteren, birinci basamak mantığı için Kalish ve Montague dizgeli bir kanıt kutusudur.
InfopageDemosTextPrefix6: Bu,
InfopageDemosTextItalics6: Deductive Logic
InfopageDemosTextSuffix6: adlı ders kitabındaki Goldfarb'ın Lemmon tarzındaki doğal türetimli kanıtıdır.
InfopageDemosText7: İşte bir üçgenin kenarlarının açıortaylarının her zaman bir noktada buluştuğunun bir kanıtı (bir noktanın bir parçanın, ancak ve ancak o parçanın uç noktalarından eşit uzaklıktaysa o parçanın açıortayı üzerinde olduğu varsayımından hareketle). "F(x,y)” "x, y üzerindedir"; “g(y,z)” "y ve z tarafından verilen segmentin açıortayı"; “h(x,z)” "x ile z arasındaki mesafe" ifadelerinin kısaltmalarıdır.
InfopageDemosText8: (Değişkenlerin sayısı yüzünden bunun, başlangıçta yüklenmesi zaman alabilir. Bir kere yüklendikten sonra değişikliklere hızlıca tepki verecektir.)
InfopageDemosTextPrefix9: İşte Russell teoreminin iki kanıtı daha, bu sefer P.D. Magnus'un ücretsiz ve açık ders kitabı
InfopageDemosTextLinkA9: Forall x
InfopageDemosTextInfixA9:'den dizge QL'nin bir versiyonunu ve Forall x'in
InfopageDemosTextLinkB9: Calgary Remix
InfopageDemosTextSuffix9:'inden FOL dizgesini kullanıyoruz.
InfopageDemosText10: Formüllerin ayrıştırılma şeklini (yüklemlere yönelik argümanların etrafındaki parantezleri düşürürek) Forall x'in görüntü tarzına uygun düşmek için değiştirmiş olduğumuzu unutmayınız.
InfopageDemosText11: Bu, bir yüklem soyutlama kuralı kullanarak bir kavrama kalıbı örneğinin nasıl kanıtlandığını gösteren Birli İkinci Basamak Mantık için Kalish ve Montague dizgeli bir kanıt kutusudur.
InfopageDemosText12: Bu, yine bir yüklem soyutlama kuralından yararlanan keyfi (sonlu) Çoklu İkinci Basamak Mantık dizgesi içerisinde her ilişkinin bir tersinin olduğunun kanıtıdır.
InfopageDemosTextPrefix13: Bu, bir temel küme teorisi dizgesinde bir geçişli kümenin kuvvet kümesinin geçişli olduğunun bir kanıtıdır (alıştırma 3, bölüm 3.3 Velleman'ın
InfopageDemosTextItalics13: Deductive Logic
InfopageDemosTextSuffix13: adlı kitabından).
InfopageDemosTextPrefix14: İşte Hardegree'nin
InfopageDemosTextLink14: Modal Logic
InfopageDemosTextSuffix14: tarzında, K5 ve KTB önermeli kipler mantığının doğal türetim dizgeleri içinde aksiyom 5 ve B'nin kanıtları.
InfopageDemosTextPrefix15: Bunlar, daha güzel görünen mantıksal semboller için
InfopageDemosTextLink15: Fira Logic
InfopageDemosTextSuffix15:'i kullanır ve her bir alt kanıtın kapsamını görsel olarak belirtmeye yardım eden korumalar kullanır.
InfopageDemosTextPrefix16: İşte, Hardegree'nin
InfopageDemosTextLink16: Modal Logic
InfopageDemosTextSuffix16: adlı yapıtındaki MPL dizgesine dayanan, naifçe nicelleştirilmiş kipler mantık dizgesi içindeki Barcan Formülünün bir kanıtı.
InfopageDemosTextPrefix17: Carnap,
InfopageDemosTextLink17: ProofJS
InfopageDemosTextSuffix17: sayesinde dizili kalkülüsteki kanıtları destekler.
InfopageDemosText18: Desteklenen dizgeler arasında, Gentzen'in orijinal LK ve LJ'sinin önermeler ve birinci basamak çeşitlemeleri bulunmaktadır.
InfopageDemosTextPrefix19: Carnap ayrıca bir JSON API'si içerir, bu da tarayıcı içi kanıt denetimi için geri planda Carnap kullanan saf JavaScript GUI'leri oluşturmayı mümkün kılar. İşte size
InfopageDemosTextLink19: Kevin Klement'in, P.D. Magnus'un Forall x dizge SL'ni kullanan forallx kanıt denetleyicisinden
InfopageDemosTextSuffix19: uyarlanmış böyle bir GUI örneği.
InfopageDemosText20: 17. örnek

InfopageWhy1: Carnap Ne İşe Yarar?
InfopageWhy2: Carnap'ı eğitimcilerin, öğrencilerin ve mantık üzerine çalışan araştırmacıların kullanması amaçlanmaktadır. Carnap, eğitimcilerin etkileşimli alıştırmalar ve öğretim materyalleri oluşturmasını ve öğrencilerin neyin ne olduğunu belirlemek için anlamsal ve sözdizimsel yöntemleri öğrenirken hızlı ve yararlı geri bildirim almalarını mümkün kılar. Carnap, ayrıca alışılmışın dışında biçimsel dizgelerle ilgilenen araştırmacıların bilgisayar destekli mantıksal araştırma için kanıt denetimi ve anlamsal araçları hızla prototip haline getirmelerini sağlar.

InfopageUsage1: Carnap'ı şu anda nasıl kullanabilirim?
InfopageUsage2: Carnap'ı kendi sınıfınızda mantık öğretmek için kullanabilirsiniz!
InfopageUsagePrefix3: Tek yapmanız gereken
InfopageUsageLinkA3: bir hesap oluşturmak
InfopageUsageInfix3: ve ardından eğitmen olarak kaydolmak için
InfopageUsageLinkB3: iletişime
InfopageUsageSuffix3: geçmek.
InfopageUsage4: Eğitimci olduğunuzda, dersinizi yürütmek ve ödevlere otomatik olarak not vermek için şu anda bulunduğunuz carnap.io adlı bu siteyi kullanabilirsiniz.
InfopageUsagePrefix5: Burada barındırılan ücretsiz
InfopageUsageLink5: ders kitabından
InfopageUsageSuffix5: problemleri öğrencilerinize verebilir veya kendi ders kitabınızı kullanabilir ve kendi tercih ettiğiniz dizge için otomatik olarak puanlanmış problem setleri oluşturabilirsiniz.
InfopageUsagePrefix6: Carnap şu anda doğruluk tablolarının, çevirinin ve ayrıştırma alıştırmalarının yanı sıra Kalish ve Montague'nün
InfopageUsageItalicsA6: Logic
InfopageUsageInfixA6: Bergmann ve Moore'un
InfopageUsageItalicsB6: Logic Book
InfopageUsageInfixB6: Hardegree'nin
InfopageUsageItalicsC6: Modal Logic
InfopageUsageInfixC6: P.D. Magnus'un
InfopageUsageItalicsD6: Forall x
InfopageUsageInfixD6:  ve
InfopageUsageItalicsE6: Forall x'in Calgary Remix'i
InfopageUsageSuffix6: adlı yapıtlarındaki biçimsel dizgelerle uyumlu türetimleri desteklemektedir.
InfopageUsage7: Ancak, projenin tutkusu azami ölçüde kapsayıcı olmaktır. Bu nedenle, favori dizgeniz desteklenmiyorsa bize bildirin, onu da eklemeye çalışalım.
InfopageUsagePrefix8: Olası eğitimciler için yardımcı belgeler
InfopageUsageLink8: burada
InfopageUsageSuffix8: bulunabilir.

InfopageName1: Neden “Carnap”?
InfopageName2: Carnap, adını yukarıda alıntılanan filozof Rudolf Carnap'tan almıştır.
InfopageName3: Carnap (filozof) mantığa hoşgörülü ve deneysel bir yaklaşımın savunucusuydu. Carnap (program) tasarımı gereği çoğulcudur. Çıkarım kuralları bildirimsel olarak belirtilir ve belirli bir dil için zaten sağlananlara yeni mantıklar eklemeyi kolaylaştırır. Çıkarımların doğru olup olmadığını denetlemeye yönelik algoritmaların çok çeşitli dillere uygulanabilir olması yeni dillerin tanıtılmasını kolaylaştırır.
InfopageName4: Carnap'ın (filozof) mantıksal tipler ve onları görmezden gelmenin sizi pek iyi çalışmayan inançlarla nasıl baş başa bırakabileceği hakkında da söyleyecek çok şeyi vardı. Carnap (program), kodun doğruluğunu sağlamak için bir mantıksal tipler teorisi kullanan, duruk yazımlı arı işlevsel bir programlama dili olan Haskell'de yazılmıştır.

InfopageWho1: Kim Carnap'ı Kullanır?
InfopageWho2: Carnap ilkin Kansas Eyalet Üniversitesi'nde geliştirilmişti, ancak artık dünya çapında düzinelerce kolej ve üniversitede kullanılıyor. İşte (tamamlanmamış) bir liste:

InfopageHow1: Carnap Nasıl Çalışır?
InfopageHow2: İşin aslı, bu bir parça teknik bir konu. İşin içinde birkaç farklı el becerisi var.
InfopageHowPrefix3: Esasen Haskell'in yazım dizgesi, farklı sözlük kategorilerini veri türleri olarak temsil etmeyi, (
InfopageHowLink3: bu yazıda
InfopageHowSuffix3: anlatılan yönteme benzer bir şey kullanarak) bu sözlüksel kategori veri tiplerini bir sözlüğü temsil eden daha büyük bir veri tipinde birleştirmeyi ve bir sözlüğün farklı öğelerinin dilbilgisel bir şekilde birbirine uygulanmasının sonucu olarak bir dili tanımlamayı olanaklı kılar.
InfopageHow4: Sonuç olarak, Carnap'ı kullanarak, önceden tanımlanmış sözcük kategorilerini bir araya getirmenin sonucu olarak bir dil tanımlayabilirsiniz. Haskell'in yazım öbekleri sayesinde, dilleriniz, kurucu sözlük kategorilerinin kendileriyle birlikte taşıdığı çeşitli yararlı özellikleri miras alacaktır (örneğin, Boolecu eklemler için sözcük kategorisi içeren diller, "ve" simgesinin nasıl ayrıştırılacağını ve görüntüleneceğini veya bağlaçlarının anlamsal değerlerinden bir tümel evetlemenin anlamsal değerinin nasıl hesaplanacağını otomatik olarak bilir). Ayrıca Haskell'in duruk yazımı ve sözcük kategorilerini tipler olarak temsil etme becerisi nedeniyle, programı derlemeye çalıştığınızda dilbilgisine aykırı bir ifadeyle sonuçlanabilecek herhangi bir programlama hatasının algılanacağı garanti edilir.
InfopageHow5: Geniş bir dil öbeğini (sözcük kategorilerini bir araya getirmenin sonucunda) tek tip olarak temsil ederek, aynı zamanda onları tek tip olarak manipüle edebiliyoruz. Özellikle, değişken değiştirimi, anlamsal değerlendirme, β-normalleştirme, yüksek dereceli birleştirme gibi şeyler için tamamen genel algoritmalar kullanabiliriz… sözgelimi, yalnızca kabul edilebilir çıkarım kuralları bildirimini kullanarak kanıtların doğruluğunu denetlemek gibi gereksinim duyduğunuz tüm iyi şeyler. Sonuç olarak bu algoritmalar için sadece bir kez kod yazmamız yeterli; daha sonra bu kodu Carnap çerçevesinde tanımlanabilecek herhangi bir dilde otomatik olarak kullanabiliriz.
InfopageHowPrefix6: Yani işin özü bu. Ayrıntılar hakkında daha fazla bilgi edinmek isterseniz kodu inceleyebilir, bir geliştiriciyle konuşabilir veya
InfopageHowLink6: bu makaleye
InfopageHowSuffix6: göz atabilirsiniz.

InfopageContributing1: Nasıl Katılabilirim?
InfopageContributingPrefix2: Carnap'ı desteklemek istiyorsanız, lütfen bizi
InfopageContributingLink2: Github
InfopageContributingSuffix2:'da yıldızlamayı unutmayınız.
InfopageContributing3: Önerileriniz, özellik istekleriniz veya hata raporlarınız varsa Github'da sorun oluşturabilirsiniz.
InfopageContributingPrefix4: Genel sorular veya tartışmalar için bize,
InfopageContributingLinkA4: Matrix
InfopageContributingInfixA4:'ten, IRC'ye köprülü
InfopageContributingLinkB4: ircs://irc.libera.chat:6697/carnap
InfopageContributingInfixB4: adresinden veya
InfopageContributingLinkC4: e-posta
InfopageContributingSuffix4: üzerinden de ulaşabilirsiniz.
InfopageContributing5: Projeye kod katkısı vermek isterseniz (yeni bir birleştirme algoritmasından, bir CSS ince ayarına veya pandoc şablonuna kadar herhangi bir şey) Github'da bir çekme isteğine koymanız yeterlidir!



# templates/auth-layout.hamlet, templates/default-layout.hamlet
LayoutAbout: Hakkında
LayoutBook: Kitap
LayoutMessage: İleti
LayoutUserHome: Kullanıcı Ana Sayfa
LayoutInstructorHome: Öğretici Ana Sayfa
LayoutSharedDocuments: Paylaşılmış Belgeler
LayoutSharedDocumentation: Belgeleme
LayoutLogout: Çıkış
LayoutLogin: Giriş

# templates/documentIndex.hamlet

DocumentIndexFilterByTag: Etikete Göre Süz
DocumentIndexPubliclyShared: Herkesle Paylaşılmış
DocumentIndexInstructorsOnly: Yalnızca Öğreticiler

# templates/passwordEntry.hamlet

PasswordEntryRequest: Bu ödev için lütfen erişim anahtarını giriniz

# templates/register.hamlet

RegisterNeedTo: Görünüşe Göre Kayıt Olmanız Gerekiyor
RegisterPleaseEnter: Lütfen aşağıdaki bilgileri giriniz:

# templates/review.hamlet

ReviewNothingToReview: İncelenecek hiçbir şey yok!
ReviewAllProblems: Tüm Problemler
ReviewNeedingReview: İnceleme Gerekiyor

# templates/carnap-book.hamlet

CarnapBookTableOfContents: İçindekiler::
CarnapBookChapters: Bölümler:
CarnapBookChapter: Bölüm
CarnapBookAppendix: Ek
CarnapBookSpecialSections: Özel Kesimler:
CarnapBookIndexOfRules: Kurallar Dizini
CarnapBookLicense: altında lisanslıdır.
