name: Automatically build Carnap and Carnap-GHCJS
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v6
      with:
        name: jade-carnap
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    # this pulls in client also
    - run: nix-build -A server
    - run: nix-shell --run "echo OK"
